:time_estimate: 2

= Quiz: OpenStack Services and Cloud-Native Applications

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Assess the learner’s understanding of the purpose and utility of the additional OpenStack services.

WARNING: Pending Review

== Questions

1. Which of the following OpenStack services would be useful for a Customer Relationship Management system (CRM) which stores data in a relational database that runs as another server instance in the same OpenStack cluster?

* [ ] Shared Filesystems (Manila)
* [ ] Object Store (Swift)
* [ ] Load Balancer (Octavia)
* [ ] DNS Service (Designate)
* [ ] Orchestration (Heat)
* [ ] Placement service (Placement)
* [ ] Key Management (Barbican)

2. Which of the following OpenStack services would be useful for a mobile Customer Support Management system which provides a scalable REST API layer designed to run more or less server instances according to load from end-users?  The Customer Support Management system enables customers to upload photos as objects, directly from their cell phones, to help with troubleshooting issues.

* [ ] Shared Filesystems (Manila)
* [ ] Object Store (Swift)
* [ ] Load Balancer (Octavia)
* [ ] DNS Service (Designate)
* [ ] Orchestration (Heat)
* [ ] Placement service (Placement)
* [ ] Key Management (Barbican)

3. Which of the following OpenStack services would be useful for a Machine Learning platform which enables Data Scients to train models and later expose those models, with a dynamically generated URL, on compute nodes with powerful GPUs, to ensure quick response times? During training, the Data Scientists need to share data as regular files with Mathematicians who are not using the platform but rely on desktop applications.

* [ ] Shared Filesystems (Manila)
* [ ] Object Store (Swift)
* [ ] Load Balancer (Octavia)
* [ ] DNS Service (Designate)
* [ ] Orchestration (Heat)
* [ ] Placement service (Placement)
* [ ] Key Management (Barbican)
