:time_estimate: 1

= Quiz: OpenStack Services and IT Infrastructure

_Estimated reading time: *{time_estimate} minute*._

Objective::

Assess the learner’s understanding of the purpose and utility of the OpenStack administration services.

== Questions

1. Which of the following OpenStack services addresses the need an OpenStack Administrator has for grouping API resources so they can be managed by different teams of OpenStack Operators?

* [ ] Identity (Keystone)
* [ ] Dashboard (Horizon)
* [ ] Bare Metal Provisioning (Ironic)
* [ ] Metering (Ceilometer)

2. Which of the following OpenStack services addresses the need an OpenStack Administrator has for instantaneous data on usage of CPU and memory from compute nodes, to assess if they are idle or overutilized by application workloads?

* [ ] Identity (Keystone)
* [ ] Dashboard (Horizon)
* [ ] Bare Metal Provisioning (Ironic)
* [ ] Metering (Ceilometer)

3. Which of the following OpenStack services addresses the need an OpenStack Administrator has for providing physical machines for an application that requires direct access to hardware devices and for which it is not possible to provide pass-through devices for a virtual machine?

* [ ] Identity (Keystone)
* [ ] Dashboard (Horizon)
* [ ] Bare Metal Provisioning (Ironic)
* [ ] Metering (Ceilometer)
