= Answers to the Review Quiz

WARNING: Pending Review

== Red Hat OpenStack Services

1. True or false: Usage of Cinder and Neutron is optional, though most real-world applications will require both.

* [x] *True* +
_Correct: applications could run on VMs which have only ephemeral storage from Nova and no network connectivity to elsewhere, but it is uncommon._

* [ ] False +
_Incorrect: most applications do require persistent storage of their VM disks and network connectivity to other applications and services, but these are not mandatory for all applications on OpenStack._

2. True or False: Glance is an alternative image service for OpenStack clusters which do not run Swift or any other form of object storage.

* [ ] True +
_Incorrect: Glance images are not media files, which would typicaly be stored in object storage. They are disk images for server boot disks._

* [x] *False* +
_Correct: Glance is not an alternative nor related to Swift and object storage. Glance is related to Nova and Cinder, because Glance provides boot images for server instances (Nova) and those images could initialize a persistent root disk volume (Cinder)._

3. True or False: Neutron provides network connectivity for server instances inside an OpenStack cluster. To provide network connectivity with external servers, including instances in other clusters, you require additional networking services such as Octavia and Designate.

* [ ] True +
_Incorrect: Neutron also provides tenant networks and floating IPs, which enable bidirectional connectivity between server instances inside a cluster and devices or servers outside the cluster._

* [x] *False* +
_Correct: Neutron does not need Octavia load balancers, Designete DNS zones, or any other OpenStack service to provide connectivity between server instances and services or servers outside an OpenStack cluster._

4. True or False: Octavia can only provide simple IP load balancers (layer 3). More sophisticated load balancer needs (layer 7) require a specialized application such as HAproxy or Squid.

* [ ] True +
_Incorrect: Octavia provides both layer 3 (IP) and layer 7 (HTTP and TLS) load balancers._

* [x] *False* +
_Correct: Octavia provides HTTP and TLS load balancers by itself, without need for additional software or services._

5. True or False: Though it is common exposing Swift objects to outside an OpenStack cluster, to clients on the Internet, it is *not* common to expose Manila file shares for the same clients.

* [x] *True* +
_Correct: File sharing protocols, such as NFS, were not designed for usage over the internet, while the Swift and S3 APIs for object storge were indeed designed for such use cases._

* [ ] False +
_Incorrect: Exposing Manila file shares over the internet would incurr significant technical and security challenges, because commmon file sharing protocols were designed for usage over local area networks (LANs)._

6. True or False: For most applications, object storage using the S3 API is a drop-in replacement for operating system file system calls.

* [ ] True +
_Incorrect: Using S3 object storage instead of operating system files requires designing an application for the S3 API instead of for file system calls._

* [x] *False* +
_Correct: Even thought there are "S3 filesystems" for Linux and other operating systems, capabilities of file and object storage differ significantly and only very simple applications would work reliabily with a translation layer._

7. True or False: Barbican provides a solution for the common issue of leaking access credentials hardcoded in source code stored in GitHub repositories.

* [x] *True* +
_Correct: by storing access tokens, user/passwords, and certificates required for accessing middleware and external services on Barbican, applications do not leed those access credentials stored on their virtual machine images and disks, much less on their source code._

* [ ] False +
_Incorrect: If you store access credentials on Barbican, there is no reason to store them also in application source code._

8. True or False: Heat orchestrates running multiple instances of the same application running in multiple, independent OpenStack clusters, for geolocation and disaster recovery.

* [ ] True +
_Incorrect: Heat orchestrates OpenStack API resources inside a single OpenStack cluster._

* [x] *False* +
_Correct: Heat cannot orchestrate OpenStack API resources in multiple OpenStack clusters. It is intended to simplify management of the many API resources that make a single application instance, in a single project. It is not designed by itself to solve requirements of geolocation and disaster recovery._

9. True or False: Designate enables automated workflows where new applications are deployed and immediately get assigned human-readable URLs.

* [x] *True* +
_Correct: Designate enables programatic or automatic assignment of DNS names to servers, load balancers, and floating IP addresses._

* [ ] False +
_Incorrect: Designate is OpenStack's dynamic DNS service and it can work integrated with Nova, Neutron, and Octavia._

10. True or False: Plamement and Ceilomer may seem to be related, because both track the usage of compute capacity by applications on OpenStack clusters, however, they are actually unrelated and provide different data: Placement is about static usage of resources, like how many virtual CPUs are available for creating more server instances, while Ceilometer is about dynamic usage of resources, like how much CPU is in use right now with multiple simultaneous end-users accessing applications.

* [x] *True* +
_Correct: While data from Placement affects scheduling of new server instances by Nova, data from Ceilometer is about the existing instances and their load on compute nodes._

* [ ] False +
_Incorrect: Data from Placement and Ceilometer is *not* correlated because, for example, an application VM might allocate many virtual CPUs and still be iddle, with no noticeable load from its end-sers, so those virtual could be CPUs iddle._

11. True or False: The Horizon dashboard provides long-term performance metrics and capacity planning estimation based on data from Ceilometer.

* [ ] True +
_Incorrect: Horizon does not provide storage for Ceilometer metrics and cannot use them for forecasting capacity or assessing peak times of compute capacity compute usage._

* [x] *False* +
_Correct: Horizon can only provide views of instantaneous data of current cluster activity becasue that is all the data that is available from Ceilometer alone._

12. True or False: The Ironic service enables automated management of compute nodes in an OpenStack cluster.

* [ ] True +
_Incorrect: Ironic was used for compute node management in previous releases of Red Hat OpenStack platform, as part of the undercloud, but it is *not* used for that with Red Hat OpenShift on OpenStack anymore._

* [x] *False* +
_Correct: Red Hat OpenShift on OpenStack uses Ironic to provide physical servers as server instances in OpenStack projects. These servers cannot become OpenStack compute nodes while being managed by Ironic._
