= Demo: Exploring an OpenStack Cluster

Objective::

Demonstrate how a larger cluster looks from the perspectives of Operators and Administrators.

WARNING: Work In Progress

== Recording

This demonstration will be recorded and the video linked from here, so learners can watch the video and optionally try to replicate it by themselves.

== Environment

There is no demo environment for now. Presenters must be able to provide their own environment, which would ideally be a larger OpenStack cluster than previous demos. Besides domains, projects, server flavors, floating ips, tenant networks, and predeployed worloads, it requires multiple AZs and host aggregates, thus a larger number of compute nodes. No need to provide multiple regions and additional cells beyond cell0 and cell1, but if such an environment is available for recording the video, it would be even beter.

The demo environment must also provide a user workstation preconfigured with the OpenStack client and a web browser to access the Horizon dashboard.

== Demonstration

// Not sure how/if to include cells in the demonstration, but if there's an easy way of showing them without showing OpenShift custom resources and pods, please do it.

1. Using the OpenStack client, as an administrator, list the regions, azs, and host aggregates of the cluster.

2. Using Horizon, as an administrator, list the regions, azs, and host aggregates of the cluster. Also show API endpoints from Keysone and highlight each endpoint belongs to region.

3. Still in Horizon, enter a domain/project and show a workload. Select its server instances and show that those instances refer to AZ and region. Ideally, have a workload with multiple servers behind a load balancer, and those servers are on different AZs.

4. Show the attributes of a couple host aggregates and of a couple server flavors, and show the attributes which match each other.

5. Show workloads using different server flavors, which map to different host aggregates. Show they run on compute nodes which match the host aggregate.

6. Switch to an operator user (member) and show it cannot list host aggregates and compute nodes but can list regions and azs.

7. Show the operator can see attributes of server instances which refer to regions, and azs. Show also the operator can see attributes of server flavors.

8. Switch back to an administrator and show the special domain and projects for cluster-wide shared API resources.

This ends the demonstration.
