= Review Quiz: Multi-Tenancy and Topology in Red Hat OpenStack

Objective::

Assess the learner's understanding of OpenStack multi-tenancy and topology mechanisms.

WARNING: Pending Review.

// Deviating from the True/False questions from previous chapters on purpose.

// This review quiz is shorter not only because the chapter has fewer sections than previous chapters, but because multi-tenancy and topology are mostly administrator concerns and this course focus on operator tasks.

== Questions

1. An OpenStack Administrator needs to support, on the same cluster, two business units which used to be independent companies, before a merger, and must continue using each of their legacy enterprise authentication system and each have their own team of OpenStack Operators. How can OpenStack support this requirement?

* [ ] Each business unit requires their own domain.
* [ ] Each business unit requires their own projects.
* [ ] Each business unit requires their own cluster.
* [ ] Each business unit requires their own region.
* [ ] Each business unit requires their own AZ.
* [ ] Each business unit requires their own host aggregate.
* [ ] Each business unit requires their own cell.

2. An OpenStack Operator needs to configure a multi-instance workload to be resilient against physical failures of network switches and uninterrupted power supplies (UPS) which are dedicated to a server rack. The data center was designed with multiple server racks, and each rack has its dedicated network switch and UPS devices. Assuming that an Administrator already configured the proper tenancy or topology mechanism, how would the operator configure its workloads?

* [ ] By spreading server instances over multiple domains.
* [ ] By spreading server instances over multiple projects.
* [ ] By spreading server instances over multiple clusters.
* [ ] By spreading server instances over multiple regions.
* [ ] By spreading server instances over multiple AZs.
* [ ] By spreading server instances over multiple host aggregates.
* [ ] By spreading server instances over multiple cells.

3. An OpenStack Operator has the member role in a project and found that the team of developers working on that project is very knowleadgeable about OpenStack and wishes to allow the team more authonomy managing API resources for their application. Can that operator grant those developers permission to manage API resources on their project?

* [ ] Yes
* [ ] No

4. An OpenStack Administrator team is concerned about "noisy neighbor" issues between applications from different teams sharing an OpenStack cluster, where one team uses too much compute capacity of the cluster and makes all other teams get lower performance from their applications. They decide to set a limit to the number of server instances in each and every project. Will this solve "noisy neighbor" issues?

* [ ] Yes
* [ ] No

5. An OpenStack Administrator created two host aggregates: one for physical machines with GPUs and another for physical machines with very large memory. Some machines have both GPUs and very large memory, should the administrator create a third host aggregate for those machines?

* [ ] Yes
* [ ] No
