= Answers to the Quiz

WARNING: Work In Progress

== Red Hat OpenStack Operations Tasks

1. Which of the following tasks are more likely to be performed by an OpenStack Operator, as opposed to a Linux System Administrator?

* [ ] Installing RPM packages inside a RHEL VM. +
_Incorrect: Linux System Administrators are more likely to perform tasks inside a VM_
* [x] Attaching a VM to a different virtual network. +
_Correct: Servers (VMs) and virtual networks are OpenStack API resources._
* [ ] Upgrading RHEL to a newer minor release inside a VM. +
_Incorrect: Linux System Administrators are more likely to perform tasks inside a VM_
* [ ] Configuring firewalld rules inside a RHEL VM. +
_Incorrect: Linux System Administrators are more likely to perform tasks inside a VM_
* [x] Configuring IP routing rules for a virtual networks. +
_Correct: Virtual networks and everything related to them are OpenStack API resources._

2. Which of the following tasks are more likely to be performed by an OpenStack Operator, as opposed to an OpenStack Administrator?

* [ ] Creating new server instances (VMs).
* [ ] Creating new virtual networks.
* [ ] Creating a new class of virtual server, with access to virtual GPUs.
* [ ] Configuring authentication to an OpenStack cluster using an LDAP server.
* [ ] Configuring virtual disk storage on a remote Ceph cluster.

3. Which of the following tasks are more likely to be performed by an OpenStack Administrator, as opposed to an Storage or Network Administrator?

* [ ] Adding new RHEL servers as compute nodes to an OpenStack cluster.
* [ ] Configure VLANs at the switch fabric.

4. Which of the following tasks are likely to NOT be required from a Red Hat OpenStack on OpenShift Administrator, as opposed to an upstream OpenStack Administrator?

* [ ] Creating operating system images to boot new server instances VMs.
* [ ] Configuring active-passive instances of OpenStack
