= OpenStack User Interfaces

*Objective:*

Describe the tools that enable OpenStack Operators to access OpenStack clusters to deploy and manage applications.

WARNING: Work In Progress

== Tools for OpenStack Administrators

As we learned in previous sections, an OpenStack Administrator manages application workloads and their virtual resources, such as servers, networks, and storage, using the OpenStack APIs. To access those APIs, Red Hat OpenShift on OpenStack provides two main tools:

The OpenStack Client::

It is a command-line tool (CLI) which provides a thin layer on the APIs of multiple OpenStack services. As a single client for multiple services, it might include commands for services that are not supported by Red Hat OpenStack or which are not enabled in a particular cluster.

The Horizon Web Interface::

It is a web application provided by an OpenStack service, so it runs in the control plane. It provides easier workflows for Operators and Administrators but may not include all OpenStack services, or may not support all APIs of the included services.

WIP
